api/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('purchases', views.Purchases_shop.as_view(), name='shop_list'),
    path(
        'purchases/<int:purchase_id>',
        views.Purchases_shop.as_view()),
    path('subscriptions', views.Subscriptions.as_view(), name='myfollow'),
    path('subscriptions/<int:username_id>', views.Subscriptions.as_view()),
    path('favorites', views.Favorites.as_view(), name='favorite_list'),
    path('favorites/<int:recipe_id>', views.Favorites.as_view()),
    path(
        'ingredients', views.GetIngredients.as_view(), name='ingredients')]

foodgram/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.flatpages import views


urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', views.flatpage, {'url': '/about/'}, name='about'),
    path('tech/', views.flatpage, {'url': '/tech/'}, name='tech'),
    path('', include('api.urls')),
    path('', include('recipes.urls')),
]


if settings.DEBUG:

    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.RecipesView.as_view(), name='index'),
    path(
        'create_recipe/',
        views.CreateRecipeView.as_view(), name='create_recipe'),
    path(
        '<str:username>/<int:recipe_id>/delete/',
        views.DeleteRecipeView.as_view(), name='delete_recipe'),
    path(
        'purchases_download/',
        views.download_purchases, name='purchases_download'),
    path('myfollow/', views.MyFollowView.as_view(), name='myfollow'),
    path('shop_list/', views.ShopListView.as_view(), name='shop_list'),
    path(
        'favorite_list/',
        views.FavoritesView.as_view(), name='favorite_list'),
    path(
        '<str:username>/',
        views.AuthorRecipeView.as_view(), name='author_recipe'),
    path(
        '<str:username>/<int:recipe_id>/',
        views.RecipeDetailView.as_view(), name='recipe'),
    path(
        '<str:username>/<int:recipe_id>/edit/',
        views.UpdateRecipeView.as_view(), name='recipe_edit'),
]

recipes/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator

User = get_user_model()


class Recipe(models.Model):
    title = models.TextField(
        'Название рецепта',
        default=None)
    ingredients = models.ManyToManyField(
        'Ingredient', blank=True, through='RecipeIngridient',
        verbose_name='Ингредиенты')
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='recipes',
        verbose_name='автор рецепта')
    diets = models.ManyToManyField(
        'Diet', blank=True, related_name='recipe_set', verbose_name='рацион')
    description = models.TextField(verbose_name='описание рецепта')
    cooking_time = models.IntegerField(
        validators=[MinValueValidator(1)], verbose_name='время приготовления')
    image = models.ImageField(
        upload_to='recipes/')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'


class Ingredient(models.Model):
    title = models.CharField(
        unique=True, max_length=300, verbose_name='название')
    dimension = models.CharField(max_length=300, verbose_name='размерность')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Ингредиенты'


class RecipeIngridient(models.Model):
    ingredient = models.ForeignKey(
        Ingredient,
        on_delete=models.CASCADE,
        related_name='ingredient',
        verbose_name='ингредиент'
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='ingredient_recipes',
        verbose_name='рецепт ингредиента'
    )
    amount = models.IntegerField(
        validators=[MinValueValidator(1)], verbose_name='значение')

    def __str__(self):
        return self.recipe.title

    class Meta:
        verbose_name = 'Ингредиент рецепта'
        verbose_name_plural = 'Ингредиенты рецепта'


class Diet(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)
    checkbox_style = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Рацион'


class FollowUser(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='follower')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='following')

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_subscription'),
        ]
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'


class FavoritesRecipe(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='favorites')
    following_recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name='favorites')

    class Meta:
        verbose_name_plural = 'Избранные рецепты'


class Purchases(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='shoping_list')
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE,
        related_name='shoping_list')

    class Meta:
        verbose_name_plural = 'Покупки'

recipes/forms.py
from django import forms
from .models import Diet, Recipe, Ingredient, RecipeIngridient
from .utils import get_ingredients_from_form
from django.shortcuts import get_object_or_404


class RecipeForm(forms.ModelForm):

    class Meta:
        model = Recipe
        fields = [
            'title',
            'diets',
            'ingredients',
            'cooking_time',
            'description',
            'image']
        localized_fields = '__all__'

        widgets = {'title': forms.TextInput(attrs={'class': 'form__input'}),
                   'diets': forms.CheckboxSelectMultiple(
                       choices=[Diet.objects.all()]),
                   'cooking_time': forms.TextInput(
                       attrs={'class': 'form__input'}),
                   'description': forms.Textarea(
                       attrs={'class': 'form__textarea', 'rows': 8}),
                   'image': forms.FileInput(
                       attrs={'class': 'form__file-button'})}

    def clean(self):
        is_tags, is_ingredient = False, False
        for key in self.data.keys():
            if 'tags' in key:
                is_tags = True
            if 'nameIngredient' in key:
                is_ingredient = True
        if not is_tags:
            self.add_error('diets', 'Отсутствует рацион, поставьте галочки')
        if not is_ingredient:
            self.add_error('ingredients', 'Необходимо добавить ингредиенты')

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.save()
        instance.diets.clear()
        for title in self.data.getlist('tags'):
            diet = get_object_or_404(Diet, title=title)
            instance.diets.add(diet)
        ingredients = get_ingredients_from_form(self.data)
        RecipeIngridient.objects.filter(recipe=instance).delete()
        for title, amount, dimension in ingredients:
            ingredient = get_object_or_404(Ingredient, title=title)
            RecipeIngridient.objects.create(
                ingredient=ingredient, recipe=instance, amount=amount)
        return instance

recipes/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls.base import reverse_lazy
from .models import (
    Recipe, User,
    FollowUser, FavoritesRecipe, Purchases,
    RecipeIngridient)
from django.views.generic import (
    ListView,
    DetailView, CreateView,
    UpdateView, DeleteView)
from .forms import RecipeForm
from django.http import HttpResponse
from .utils import get_sort_list_tags
from django.db.models import Sum
from foodgram.settings import PAGINATE_BY
import csv
import logging
logger = logging.getLogger(__name__)


class RecipesView(ListView):
    """Список рецептов """
    template_name = 'index.html'
    paginate_by = PAGINATE_BY

    def get_queryset(self):
        queryset = Recipe.objects.all()
        sort_list = get_sort_list_tags(self.request)
        if sort_list:
            queryset = Recipe.objects.filter(
                diets__slug__in=sort_list).distinct()
        return queryset


class FavoritesView(ListView):
    """Список избранных рецептов."""
    model = FavoritesRecipe
    template_name = 'recipes/followrecipe_list.html'
    paginate_by = PAGINATE_BY

    def get_queryset(self):
        pk = FavoritesRecipe.objects.filter(
            user=self.request.user).values('following_recipe')
        queryset = Recipe.objects.filter(id__in=pk)
        sort_list = get_sort_list_tags(self.request)
        if sort_list:
            queryset = Recipe.objects.filter(
                id__in=pk, diets__slug__in=sort_list).distinct()
        return queryset


class RecipeDetailView(DetailView):
    """Детали рецепта."""
    model = Recipe
    template_name = 'recipes/single_page.html'
    pk_url_kwarg = 'recipe_id'


class AuthorRecipeView(ListView):
    """Список рецептов автора."""
    template_name = 'recipes/author_recipe_list.html'
    paginate_by = PAGINATE_BY

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        sort_list = get_sort_list_tags(self.request)
        queryset = Recipe.objects.filter(author=user)
        if sort_list:
            queryset = Recipe.objects.filter(
                diets__slug__in=sort_list, author=user).distinct()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(
            AuthorRecipeView, self).get_context_data(**kwargs)
        context['author_recipe_name'] = get_object_or_404(
            User, username=self.kwargs.get('username'))
        return context


class MyFollowView(LoginRequiredMixin, ListView):
    """Подписка на автора рецепта."""
    model = FollowUser
    template_name = 'recipes/followuser_list.html'
    paginate_by = 3

    def get_queryset(self):
        queryset = FollowUser.objects.filter(user=self.request.user)
        return queryset


class CreateRecipeView(LoginRequiredMixin, CreateView):
    """Создание рецепта."""
    form_class = RecipeForm
    template_name = 'recipes/form_recipe.html'
    pk_url_kwarg = 'recipe_id'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class UpdateRecipeView(LoginRequiredMixin, UpdateView):
    """Редактирование рецепта."""
    model = Recipe
    form_class = RecipeForm
    template_name = 'recipes/form_recipe.html'
    pk_url_kwarg = 'recipe_id'
    success_url = reverse_lazy('index')


class DeleteRecipeView(DeleteView):
    """Удаление рецепта."""
    model = Recipe
    template_name = "recipes/recipe_congirm_delete.html"
    pk_url_kwarg = 'recipe_id'
    success_url = reverse_lazy('index')

    def get_queryset(self):
        owner = self.request.user
        return self.model.objects.filter(author=owner)


class ShopListView(ListView):
    """Список покупок."""
    model = Purchases
    template_name = 'shop_list.html'
    context_object_name = 'purchases'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            queryset = Recipe.objects.filter(
                shoping_list__user=self.request.user)
        else:
            try:
                queryset = Recipe.objects.filter(
                    pk__in=self.request.session['purchase'])
            except KeyError:
                queryset = []
        return queryset


def download_purchases(request):
    if request.user.is_authenticated:
        recipes_list = Recipe.objects.filter(shoping_list__user=request.user)
    else:
        recipes_list = Recipe.objects.filter(
            id__in=request.session.get('purchase'))
    list_ingredients = list(
        RecipeIngridient.objects.filter(recipe__id__in=recipes_list)
        .values('ingredient__title', 'ingredient__dimension')
        .annotate(total=Sum('amount'))
    )
    response = HttpResponse(content_type='text/plain')
    response['Content-Disposition'] = 'attachment; filename=Purchases_list.txt'
    writer = csv.writer(response)
    writer.writerow(['Наименование', '(единица измерения)', 'Кол-во'])
    for item in list_ingredients:
        title = item['ingredient__title']
        dimension = item['ingredient__dimension']
        amount = item['total']
        writer.writerow([title, ('({})').format(dimension), amount])
    return response


def page_not_found(request, exception):
    return render(
        request,
        'misc/404.html',
        {'path': request.path},
        status=404
    )


def server_error(request):
    return render(request, 'misc/500.html', status=500)

recipes/templates/recipes/author_recipe_list.html
{% extends "base.html" %} {% load static %}
{% block title %}Рецепты{%endblock%}
{% block static_css %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}
{% block menu %}
    {% include "menu.html" %}
{%endblock%}
{% block menu_title %} {{author_recipe_name.get_full_name}} {%endblock%}
{% block menu_diet %}
    {% include "menu_diet.html" %}
{%endblock%}
{% block content %}
<div class="author-subscribe" data-author={{author_recipe_name.id}}>
    <p style="padding: 0 0 2em 0;">
        {% include "includes/button_subscribe.html" with author=author_recipe_name %}
    </p>
</div>
{% include "includes/recipe_item.html" with author_recipe=recipe %}
{% include "paginator.html" with items=page paginator=paginator %}
{%endblock%}
{% block js %}
    {% if user.is_authenticated %}
        <script src="{% static 'js/components/MainCards.js' %}"></script>

        <script src="{% static 'js/components/Purchases.js' %}"></script>
        <script src="{% static 'js/components/Favorites.js' %}"></script>
        <script src="{% static 'js/components/Subscribe.js' %}"></script>

        <script src="{% static 'js/config/config.js' %}"></script>
        <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
        <script src="{% static 'js/components/Header.js' %}"></script>

        <script src="{% static 'js/api/Api.js' %}"></script>

        <script src="{% static 'authorRecipe.js' %}"></script>
    {%endif%}
{%endblock%}

recipes/templates/recipes/followrecipe_list.html
{% extends "base.html" %} {% load thumbnail %} {% csrf_token %} {% load static %} 
{% block title %}Избранное{%endblock%}
{% block static_css %}
    <link rel="stylesheet" href="{% static './pages/index.css' %}">
{% endblock %}
{% block menu %}
    {% include "menu.html" %}
{%endblock%}
{% block menu_title %} Избранное {%endblock%}
{% block menu_diet %}
    {% include "menu_diet.html" %}
{%endblock%}
{%block content%}
    {% if not object_list %}
        {% include "custom_page.html" %}
    {% endif %}
    {% include 'includes/recipe_item.html' %}
    {% include "paginator.html" %}
{%endblock%}
{% block js %}
    {% if user.is_authenticated %}
        <script src="{% static 'js/components/MainCards.js' %}"></script>

        <script src="{% static 'js/components/Purchases.js' %}"></script>
        <script src="{% static 'js/components/Favorites.js' %}"></script>

        <script src="{% static 'js/config/config.js' %}"></script>
        <script src="{% static 'js/components/CardList.js' %}"></script>
        <script src="{% static 'js/components/Header.js' %}"></script>

        <script src="{% static 'js/api/Api.js' %}"></script>
        <script src="{% static 'favorite.js' %}"></script>
    {%endif%}
{%endblock%}

recipes/templates/recipes/form-recipe.html
{% extends "base.html" %} {% load static %} {% block head %}
<title>{% if recipe %}Редактирование{% else %}Создание{%endif%} рецепта</title>
<link rel="stylesheet" href="{% static './pages/form.css' %}" />
{%endblock%} {% block content %}
<div class="main__header">
    <h1 class="main__title">{% if recipe %}Редактирование{% else %}Создание{%endif%} рецепта</h1>
</div>
<div class="form-container">
    <form class="form" method="post" enctype="multipart/form-data" action="{% if recipe %}{% url 'recipe_edit' recipe.author.username recipe.id %}{% else %}{% url 'create_recipe' %}{% endif %}">
        {% csrf_token %}
        <div class="form__group">
            <label for="id_name" class="form__label">Название рецепта</label>
            <div class="form__field-group">
                {{ form.title }}
                <span class="form__error"></span>
            </div>
        </div>
        <div class="form__group">
            <p class="form__label">Теги</p>
            <div class="form__field-group">
                <div class="tags">
                    {% load tags_filter %} {% for pk, choices in form.diets.field.choices %}
                    <div class="tags__item">
                        <input
                            type="checkbox"
                            name="tags"
                            id="id_{{ pk }}"
                            class="tags__checkbox tags__checkbox_style_{{ pk|get_checkbox_style_tag }}"
                            value="{{ choices.title }}"
                            {% if choices in recipe.diets.all|get_list_tag %} checked {% endif %}
                        />
                        <label for="id_{{ pk }}" class="tags__label">{{ choices }}</label>
                    </div>
                    {% endfor %} {{form.diets.non_field_errors}}
                </div>
                <span class="form__error">{{form.diets.errors}}</span>
            </div>
        </div>
        <div class="form__group">
            <label for="nameIngredient" class="form__label">Ингредиенты</label>
            <div class="form__field-group">
                <div class="form__field-group-ingredientes">
                    <div class="form__dropdown">
                        <input type="text" id="nameIngredient" class="form__input" />
                        <div class="form__dropdown-items"></div>
                    </div>
                    <input type="number" id="cantidad" class="form__input" min="0" />
                    <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                </div>
                <div class="form__field-group-ingredientes-container">
                    {%for item in recipe.ingredient_recipes.all %}
                    <div id="ing_{{ forloop.counter }}" class="form__field-item-ingredient">
                        <span>{{ item.ingredient.title }} {{ item.amount }} {{ item.ingredient.dimension }}</span><span class="form__field-item-delete"></span>
                        <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient_{{ forloop.counter }}" type="hidden" value="{{ item.ingredient.title }}" />
                        <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient_{{ forloop.counter }}" type="hidden" value="{{ item.amount }}" />
                        <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient_{{ forloop.counter }}" type="hidden" value="{{ item.ingredient.dimension }}" />
                    </div>
                    {%endfor%}
                </div>
                <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                <span class="form__error">{{form.ingredients.errors}}</span>
            </div>
        </div>
        <div class="form__group">
            <label for="id_time" class="form__label">Время приготовления</label>
            <div class="form__field-group form__field-group_time">
                {{form.cooking_time}}
                <label for="id_time" class="form__label">минут</label>
                <span class="form__error"></span>
            </div>
        </div>
        <div class="form__group">
            <label for="id_description" class="form__label">Описание</label>
            <div class="form__field-group">
                {{form.description}}
                <span class="form__error"></span>
            </div>
        </div>
        <div class="form__group">
            <span class="form__label">Загрузить фото</span>
            <div class="form__field-group">
                <label for="id_file" class="form__file-button">Выбрать файл</label>
                <input type="file" class="form__file" name="image" id="id_file" />
                <span class="form__error"></span>
            </div>
        </div>
        <div class="form__footer">
            {% if recipe %}
            <button class="button button_style_blue">Сохранить</button>
            <a style="margin-left: 2.5em;" href="{% url 'delete_recipe' recipe.author.username recipe.id %}" class="form__ingredient-link">Удалить</a>
            {% else %}
            <button class="button button_style_blue">Создать рецепт</button>
            {% endif %}
        </div>
    </form>
</div>
{%endblock%} {% block js %} {% include 'block_js.html' %}
<script src="{% static './js/utils/debouncing.js' %}"></script>
<script src="{% static 'formRecipe.js' %}"></script>
{%endblock%}

recipes/templates/recipes/form_recipe.html
{% extends "base.html" %} {% load static %}
{% block title %}{% if recipe %}Редактирование{% else %}Создание{%endif%} рецепта{% endblock title %}
{% block static_css %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}
{% block menu %}
    {% include "menu.html" %}
{%endblock%}
{% block menu_title %} {% if recipe %}Редактирование{% else %}Создание{%endif%} рецепта {%endblock%}
{% block content %}
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data" action="{% if recipe %}{% url 'recipe_edit' recipe.author.username recipe.id %}{% else %}{% url 'create_recipe' %}{% endif %}">
            {% csrf_token %}
            <div class="form__group">
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    {{ form.title }}
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        {% load tags_filter %}
                        {% for pk, choices in form.diets.field.choices %}
                            <div class="tags__item">
                                <input
                                    type="checkbox"
                                    name="tags"
                                    id="id_{{ pk }}"
                                    class="tags__checkbox tags__checkbox_style_{{ pk|get_checkbox_style_tag }}"
                                    value="{{ choices.title }}"
                                    {% if choices in recipe.diets.all|get_list_tag %} checked {% endif %}
                                />
                                <label for="id_{{ pk }}" class="tags__label">{{ choices }}</label>
                            </div>
                        {% endfor %}
                        {{form.diets.non_field_errors}}
                    </div>
                    <span class="form__error">{{form.diets.errors}}</span>
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">
                        {%for item in recipe.ingredient_recipes.all %}
                            <div id="ing_{{ forloop.counter }}" class="form__field-item-ingredient">
                                <span>{{ item.ingredient.title }} {{ item.amount }} {{ item.ingredient.dimension }}</span><span class="form__field-item-delete"></span>
                                <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient_{{ forloop.counter }}" type="hidden" value="{{ item.ingredient.title }}">
                                <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient_{{ forloop.counter }}" type="hidden" value="{{ item.amount }}">
                                <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient_{{ forloop.counter }}" type="hidden" value="{{ item.ingredient.dimension }}">
                            </div>
                        {%endfor%}
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error">{{form.ingredients.errors}}</span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    {{form.cooking_time}}
                    <label for="id_time" class="form__label">минут</label>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    {{form.description}}
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    
                    <label for="file_in" class="form__file-button">Выбрать файл</label>
                    <span id="file_name">
                        <div class="form__group">
                            <span class="form__label">{% if recipe %} Текущее фото {{ form.image.value|cut:'recipes/' }} {%endif%}</span>
                            <div class="form__field-group">
                                <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" style="width:100px;">
                            </div>
                        </div>
                    </span>
                    <input type="file" name="image" style="display: none" id="file_in" onchange="onChange()">
                
                <script>
                    function onChange() {
                    const input = document.getElementById('file_in')
                    const elem = document.getElementById('file_name')
                    elem.innerText = input.files[0].name
                    }
                </script>
                <span class="form__error">{{form.errors}}</span>
                </div>
            </div>
            <div class="form__footer">
                {% if recipe %}
                    <button class="button button_style_blue">Сохранить</button>
                    <a style="margin-left: 2.5em;" href="{% url 'delete_recipe' recipe.author.username recipe.id %}" class="form__ingredient-link">Удалить</a>
                {% else %}
                    <button class="button button_style_blue">Создать рецепт</button>
                {% endif %}
            </div>
        </form>
    </div>
{%endblock%}
{% block js %}
    {% if user.is_authenticated %}
        <script src="{% static 'js/config/config.js' %}"></script>
        <script src="{% static 'js/components/Header.js' %}"></script>
        <script src="{% static 'js/utils/debouncing.js' %}"></script>
        <script src="{% static 'js/api/Api.js' %}"></script>
        <script src="{% static 'formRecipe.js' %}"></script>
    {%endif%} 
{%endblock%}

recipes/templates/recipes/recipe_congirm_delete.html
{% extends "base.html" %} {% csrf_token %} {% load static %}
{% block title %}Удаление рецепта{%endblock%}
{% block static_css %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}
{% block menu %}
    {% include "menu.html" %}
{%endblock%}
{% block menu_title %} Удаление рецепта {%endblock%}
{% block content %}
    <div class="custom-center-block">
        <form method="post">
            {% csrf_token %}
            <p class="custom-text-block">Вы точно хотите удалить "{{object}}"?</p>
            <div class="custom-button-block">
                <button class="button button_style_blue" value="Confirm">Удалить</button>
            </div>
        </form>
    </div>
{% endblock %}

recipes/templates/recipes/recipe_list.html
{% extends "base.html" %} {% load static %}
{% block title %}Рецепты{%endblock%}
{% block static_css %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}
{% block menu %}
    {% include "menu.html" %}
{%endblock%}
{% block content %}
    <div class="main__header">
        <h1 class="main__title">Рецепты</h1>
        {% include "menu_diet.html" %}
    </div>
    {% include "includes/recipe_item.html" with recipe=recipe %}
    {% include "paginator.html" with items=page paginator=paginator%}
{%endblock%}
{% block js %} {%endblock%}